### ISSUE TITLE
Wrong gas spent in Wallets

### ISSUE THREAD

**Issue by salgozino** [EnormousCloud/api3-dao-tracker#12]
I would like to start thanking you for this dashboard! it's a great tool!.

I've noticed that In the wallets sections says for example: _Spent 0.37889 ETH in fees, Est $1272.61_, but I think that this data has a mistake. The amount in ETH is wrong and missing a few leading zeros.

I think that there is 2 leading zeros missed. It's not 0.37, should be 0.0037 eth. The USD price it's ok or very similar to what etherscan reports, at least for my staking transaction.

**Comment by EnormousCloud** [comment]
well, I wish that was just a mistake...

I believe you are quoting Burak's wallet statistics, as he is the only one with such expense for being active in the DAO.
He literally spent more than a thousand dollars just on Ethereum fees, and this is around 0.37ETH. No zeros were missing, it is real... He is just the most active and we found no bug in rendering this. Just a crazy expense which is hard to believe. And its one of the reasons it is being displayed there.

When you are looking at the wallet list you see the summary on how much it was spent on the gas in total, and it accumulates **history of all transactions fees** that were made by the wallet: voting, delegations or any other DAO events. 

- So your single staking transaction fee is accurate. 
- USD price is slightly inaccurate because it uses daily averages of the day of transaction
- This number of 0.37eth is even **lowered**, because some of the transactions (like vote execution) was not counted

**Comment by EnormousCloud** [comment]
Thanks for the details, 
you are totally right, this example illustrates the issue much better.

Whatever this is, we will fix it.

**Comment by EnormousCloud** [comment]
The fix is live.
